// Single canonical download path for the whole extension: the popup never
// calls downloads.download itself, it forwards {type: "downloadBackup"} here.
// This matters because the popup can close while the saveAs dialog is open,
// while the background outlives the dialog and can clean up afterwards.
//
// MV3 background context: a service worker in Chromium, an event page in
// Firefox. The same file must run in both, so it can only rely on the worker
// surface: service workers have no URL.createObjectURL and no FileReader.
// Blob downloads are used when available (event page); otherwise the payload
// is encoded as a data: URL by hand, which chrome.downloads accepts.
const isFirefox = typeof browser !== "undefined";
const api = isFirefox ? browser : chrome;

// Upper bound for one message payload (runtime.sendMessage has its own
// quota; fail fast with a clear error instead of a cryptic transport one).
const MAX_DOWNLOAD_BYTES = 64 * 1024 * 1024;

api.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (!message || message.type !== "downloadBackup") {
    return;
  }

  downloadBackup(message.data, message.filename)
    .then((id) => sendResponse({ ok: true, id: id }))
    .catch((error) => sendResponse({ ok: false, error: String(error?.message || error) }));

  return true; // keep the channel open, the response is async
});

// Builds a data: URL from a string without FileReader/URL.createObjectURL,
// which do not exist in service workers. TextEncoder and btoa exist in both
// workers and documents. Chunked conversion avoids blowing the call stack on
// large backups.
function stringToDataUrl(data) {
  const bytes = new TextEncoder().encode(data);
  let binary = "";
  const CHUNK = 0x8000;
  for (let i = 0; i < bytes.length; i += CHUNK) {
    binary += String.fromCharCode.apply(null, bytes.subarray(i, i + CHUNK));
  }
  return "data:application/octet-stream;base64," + btoa(binary);
}

async function downloadBackup(data, filename) {
  if (typeof data !== "string" || data.length === 0) {
    throw new Error("invalid backup payload");
  }
  if (data.length > MAX_DOWNLOAD_BYTES) {
    throw new Error("backup payload is too large");
  }
  // the filename is generated by the popup, but never trust the wire:
  // strip any directory parts so a message can't write outside Downloads
  filename = String(filename || "").split(/[\\/]/).pop();
  if (!filename || filename.length > 255) {
    throw new Error("invalid filename");
  }
  if (!api.downloads || typeof api.downloads.download !== "function") {
    throw new Error("downloads API is not available");
  }

  // Prefer a blob URL where the platform has one; fall back to an inline
  // data: URL in service workers (Chromium accepts it in downloads.download).
  let url = null;
  let isBlobUrl = false;
  if (typeof URL !== "undefined" && typeof URL.createObjectURL === "function") {
    const blob = new Blob([data], { type: "application/octet-stream" });
    url = URL.createObjectURL(blob);
    isBlobUrl = true;
  } else {
    url = stringToDataUrl(data);
  }

  const revoke = () => {
    if (isBlobUrl && url) {
      try {
        URL.revokeObjectURL(url);
      } catch (e) {}
      url = null;
    }
  };

  let id;
  try {
    id = await api.downloads.download({
      url: url,
      filename: filename,
      conflictAction: "uniquify",
      saveAs: true
    });
  } catch (error) {
    revoke();
    throw error;
  }

  const listener = (delta) => {
    if (delta?.id != id) return;
    if (delta?.state?.current == "complete") {
      api.downloads.onChanged.removeListener(listener);
      revoke();
      try {
        const shown = api.downloads.show(id);
        if (shown && typeof shown.catch === "function") shown.catch(() => {});
      } catch (e) {}
    } else if (delta?.state?.current == "interrupted") {
      api.downloads.onChanged.removeListener(listener);
      revoke();
      // the popup only learns whether the download *started*; post-start
      // states have no UI to report to (the popup may be closed), so log
      // the reason here for diagnostics
      try {
        console.warn("Backup download interrupted:", delta?.error?.current || "unknown");
      } catch (e) {}
    }
  };
  api.downloads.onChanged.addListener(listener);

  return id;
}
