// Single canonical download path for the whole extension: the popup never
// calls downloads.download itself, it forwards {type: "downloadBackup"} here.
// This matters because the popup can close while the saveAs dialog is open,
// while the background outlives the dialog and can clean up afterwards.
//
// MV3 background context: a service worker in Chromium, an event page in
// Firefox. The same file must run in both, so it can only rely on the worker
// surface: service workers have no URL.createObjectURL and no FileReader.
// Blob downloads are used when available (event page); otherwise the payload
// is encoded as a data: URL by hand, which chrome.downloads accepts.
// NOTE: `browser` exists in Firefox and (since ~2026) in Chrome too,
// so it can't be used for Firefox detection. getBrowserInfo exists only in Firefox.
const api = typeof browser !== "undefined" ? browser : chrome;
const isFirefox =
  (typeof navigator !== "undefined" && /Firefox|FxiOS/i.test(navigator.userAgent || "")) ||
  (typeof browser !== "undefined" &&
    browser.runtime &&
    typeof browser.runtime.getBrowserInfo === "function");

// Upper bound for one message payload (runtime.sendMessage has its own
// quota; fail fast with a clear error instead of a cryptic transport one).
// Kept in sync with MAX_BACKUP_BYTES in popup.js: a backup that passes the
// popup precheck must also pass here. The value accounts for the ~33%
// base64 inflation of the data: URL fallback used in service workers.
const MAX_DOWNLOAD_BYTES = 32 * 1024 * 1024;

// Last blob URL handed out but not yet revoked (its onChanged may never
// fire if an MV3 worker is suspended mid-download). Reclaimed on the next
// download instead of leaking. Data: URLs need no cleanup.
let lastBlobUrl = null;

api.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (!message || message.type !== "downloadBackup") {
    return;
  }

  downloadBackup(message.data, message.filename)
    .then((id) => sendResponse({ ok: true, id: id }))
    .catch((error) => sendResponse({ ok: false, error: String(error?.message || error) }));

  return true; // keep the channel open, the response is async
});

// Builds a data: URL from a string without FileReader/URL.createObjectURL,
// which do not exist in service workers. TextEncoder and btoa exist in both
// workers and documents. Chunked conversion avoids blowing the call stack on
// large backups.
function stringToDataUrl(data) {
  const bytes = new TextEncoder().encode(data);
  let binary = "";
  const CHUNK = 0x8000;
  for (let i = 0; i < bytes.length; i += CHUNK) {
    binary += String.fromCharCode.apply(null, bytes.subarray(i, i + CHUNK));
  }
  return "data:application/octet-stream;base64," + btoa(binary);
}

// Byte length of a string, not UTF-16 units: payloads can hold multibyte
// characters, and the limit below is bytes.
function utf8ByteLength(s) {
  if (typeof s !== "string") return 0;
  // fast path: every char is at most 4 bytes, so short strings fit for sure
  if (s.length <= MAX_DOWNLOAD_BYTES / 4) return s.length;
  try {
    return new TextEncoder().encode(s).length;
  } catch (e) {
    return s.length * 3; // conservative upper bound, never under-reports
  }
}

// downloads.download is promise-based in modern Chrome/Firefox but
// callback-only in old Chromiums (minimum_chrome_version is 88): support
// both forms instead of assuming a promise. No timeout here on purpose —
// with saveAs:true the call pends until the user picks a location.
function downloadsDownload(opts) {
  return new Promise((resolve, reject) => {
    let settled = false;
    const settleOk = (value) => {
      if (!settled) {
        settled = true;
        resolve(value);
      }
    };
    const settleErr = (error) => {
      if (!settled) {
        settled = true;
        reject(error instanceof Error ? error : new Error(String(error)));
      }
    };
    const callback = (id) => {
      let lastError = null;
      try {
        lastError = api && api.runtime && api.runtime.lastError ? api.runtime.lastError : null;
      } catch (e) {
        lastError = null;
      }
      if (lastError) {
        settleErr(new Error(lastError.message || String(lastError)));
      } else {
        settleOk(id);
      }
    };
    let maybe;
    try {
      maybe = api.downloads.download(opts, callback);
    } catch (error) {
      settleErr(error);
      return;
    }
    if (maybe && typeof maybe.then === "function") {
      maybe.then(settleOk, settleErr);
    }
    // otherwise the callback above settles the promise
  });
}

async function downloadBackup(data, filename) {
  if (typeof data !== "string" || data.length === 0) {
    throw new Error("invalid backup payload");
  }
  if (utf8ByteLength(data) > MAX_DOWNLOAD_BYTES) {
    throw new Error("backup payload is too large");
  }
  // the filename is generated by the popup, but never trust the wire:
  // strip any directory parts so a message can't write outside Downloads
  filename = String(filename || "").split(/[\\/]/).pop();
  if (!filename || filename.length > 255) {
    throw new Error("invalid filename");
  }
  // allowlist: backups are .ckz (encrypted, any inner format) or plain-text
  // exports (.json, .txt for Netscape/Header, .js for Puppeteer,
  // .py for Python Dict, .csv for CSV). Without this any sender could make
  // the browser download an executable.
  const lowerName = filename.toLowerCase();
  if (!lowerName.endsWith(".ckz") && !lowerName.endsWith(".json")
      && !lowerName.endsWith(".txt") && !lowerName.endsWith(".js")
      && !lowerName.endsWith(".cjs") && !lowerName.endsWith(".mjs")
      && !lowerName.endsWith(".py") && !lowerName.endsWith(".csv")) {
    throw new Error("invalid filename");
  }
  if (!api.downloads || typeof api.downloads.download !== "function") {
    throw new Error("downloads API is not available");
  }

  // Prefer a blob URL where the platform has one; fall back to an inline
  // data: URL in service workers (Chromium accepts it in downloads.download).
  let url = null;
  let isBlobUrl = false;
  if (typeof URL !== "undefined" && typeof URL.createObjectURL === "function") {
    const blob = new Blob([data], { type: "application/octet-stream" });
    url = URL.createObjectURL(blob);
    isBlobUrl = true;
  } else {
    url = stringToDataUrl(data);
  }

  const revoke = () => {
    if (isBlobUrl && url) {
      try {
        URL.revokeObjectURL(url);
      } catch (e) {}
      if (url === lastBlobUrl) lastBlobUrl = null;
      url = null;
    }
  };

  let id;
  try {
    id = await downloadsDownload({
      url: url,
      filename: filename,
      conflictAction: "uniquify",
      saveAs: true
    });
  } catch (error) {
    revoke();
    throw error;
  }
  // a callback-only browser resolves via lastError instead of rejecting,
  // so a missing id can still slip through: treat it as "never started"
  if (typeof id !== "number") {
    revoke();
    throw new Error("download did not start");
  }

  // Reclaim a stale blob URL from a previous download whose onChanged never
  // fired (worker was suspended), then track the new one for the same case.
  if (isBlobUrl && url) {
    if (lastBlobUrl && lastBlobUrl !== url) {
      try {
        URL.revokeObjectURL(lastBlobUrl);
      } catch (e) {}
    }
    lastBlobUrl = url;
  }

  let safetyTimer = 0;
  const cleanup = () => {
    api.downloads.onChanged.removeListener(listener);
    if (safetyTimer) {
      try {
        clearTimeout(safetyTimer);
      } catch (e) {}
      safetyTimer = 0;
    }
    revoke();
  };
  const listener = (delta) => {
    if (delta?.id != id) return;
    if (delta?.state?.current == "complete") {
      cleanup();
      try {
        const shown = api.downloads.show(id);
        if (shown && typeof shown.catch === "function") shown.catch(() => {});
      } catch (e) {}
    } else if (delta?.state?.current == "interrupted") {
      cleanup();
      // the popup only learns whether the download *started*; post-start
      // states have no UI to report to (the popup may be closed), so log
      // the reason here for diagnostics
      try {
        console.warn("Backup download interrupted:", delta?.error?.current || "unknown");
      } catch (e) {}
    }
  };
  api.downloads.onChanged.addListener(listener);
  // last resort if onChanged never fires (suspended worker, huge file):
  // drop the listener so repeated backups don't accumulate them.
  // unref (Node/test only) so this safety net never keeps the loop alive.
  try {
    safetyTimer = setTimeout(cleanup, 5 * 60 * 1000);
    if (safetyTimer && typeof safetyTimer.unref === "function") safetyTimer.unref();
  } catch (e) {}

  return id;
}
