/* Multi-format cookie serializers/parsers for Cookie Backup and Restore.
   Pure functions, no DOM or extension APIs: loaded via <script> before
   popup.js and unit-testable under Node (same pattern as locales.js).

   Formats (see the export grid in popup.html):
     json      - Standard JSON array of chrome.cookies.Cookie objects
     netscape  - Netscape cookies.txt (Wget / Curl)
     header    - HTTP "Cookie" header string: name=value; name2=value2
     puppeteer - Node.js module exporting a Puppeteer-compatible cookie array
     pydict    - Python dict literal for the `requests` library
     csv       - CSV table for Excel / audit

   Encrypted backups (.ckz) wrap the plain text of ANY format:
     - json keeps the legacy direct-array payload so old extension versions
       (and old backups) keep working both ways;
     - every other format is stored as {"format","version","payload"}.
*/

const EXPORT_FORMAT_IDS = ["json", "netscape", "header", "puppeteer", "pydict", "csv"];

const FORMAT_SHORT_NAMES = {
  json: "JSON",
  netscape: "Netscape",
  header: "Header String",
  puppeteer: "Puppeteer",
  pydict: "Python Dict",
  csv: "CSV",
};

const FORMAT_ENVELOPE_VERSION = 1;

function isKnownFormat(id) {
  return EXPORT_FORMAT_IDS.indexOf(id) !== -1;
}

function formatShortName(id) {
  return FORMAT_SHORT_NAMES[id] || String(id);
}

// ---------- shared helpers ----------

function isString(v) {
  return typeof v === "string";
}

function cookiesArrayGuard(cookies) {
  if (!Array.isArray(cookies)) throw new Error("not a cookie array");
  return cookies;
}

function csvEscapeField(v) {
  const s = v == null ? "" : String(v);
  if (s.indexOf('"') !== -1 || s.indexOf(",") !== -1 || s.indexOf("\n") !== -1 || s.indexOf("\r") !== -1) {
    return '"' + s.replace(/"/g, '""') + '"';
  }
  return s;
}

function parseBoolLoose(v) {
  if (typeof v === "boolean") return v;
  if (v == null) return null;
  const s = String(v).trim().toLowerCase();
  if (s === "" || s === "null" || s === "undefined" || s === "none") return null;
  if (s === "true" || s === "1" || s === "yes" || s === "y") return true;
  if (s === "false" || s === "0" || s === "no" || s === "n") return false;
  return null;
}

function parseNumberLoose(v) {
  if (typeof v === "number" && isFinite(v)) return v;
  if (v == null) return null;
  const s = String(v).trim();
  if (!s) return null;
  const n = Number(s);
  return isFinite(n) ? n : null;
}

// ---------- JSON (Standard) ----------

function serializeJson(cookies) {
  cookiesArrayGuard(cookies);
  return JSON.stringify(cookies, null, 2);
}

function parseJsonText(text) {
  if (!isString(text) || !text.trim()) throw new Error("empty JSON backup");
  let parsed;
  try {
    parsed = JSON.parse(text);
  } catch (e) {
    throw new Error("not a JSON backup");
  }
  if (!Array.isArray(parsed)) throw new Error("not a JSON backup");
  return parsed;
}

// ---------- Netscape (Wget / Curl) ----------

function serializeNetscape(cookies) {
  cookiesArrayGuard(cookies);
  const lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by Cookie Backup and Restore (https://github.com/AvenCores/cookies-backup-chrome)",
  ];
  for (const c of cookies) {
    if (!c || !isString(c.name) || !isString(c.value)) continue;
    const domain = isString(c.domain) ? c.domain : "";
    const path = isString(c.path) ? c.path : "/";
    const subdomains = domain.charAt(0) === "." ? "TRUE" : "FALSE";
    const secure = c.secure === true ? "TRUE" : "FALSE";
    const exp = typeof c.expirationDate === "number" && isFinite(c.expirationDate) && c.expirationDate > 0
      ? String(Math.round(c.expirationDate))
      : "0";
    // curl understands "#HttpOnly_"-prefixed domains; keep the flag round-trippable
    const domainField = c.httpOnly === true && domain && domain.indexOf("#HttpOnly_") !== 0
      ? "#HttpOnly_" + domain
      : domain;
    lines.push([domainField, subdomains, path, secure, exp, c.name, c.value].join("\t"));
  }
  return lines.join("\n") + "\n";
}

function isNetscapeText(text) {
  if (!isString(text)) return false;
  if (text.indexOf("# Netscape HTTP Cookie File") !== -1) return true;
  const lines = text.split(/\r?\n/);
  for (const line of lines) {
    const t = line.trim();
    // "#HttpOnly_"-prefixed data lines are cookies, other #-lines are comments
    if (!t || (t.charAt(0) === "#" && t.indexOf("#HttpOnly_") !== 0)) continue;
    if (line.split("\t").length >= 7) return true;
  }
  return false;
}

function parseNetscapeText(text) {
  if (!isString(text) || !text.trim()) throw new Error("empty Netscape file");
  const out = [];
  const lines = text.split(/\r?\n/);
  for (const line of lines) {
    const t = line.trim();
    if (!t || (t.charAt(0) === "#" && t.indexOf("#HttpOnly_") !== 0)) continue;
    let parts = line.split("\t");
    if (parts.length < 7) {
      // lenient fallback: split on whitespace (values with spaces still work
      // when the file uses tabs; this only helps hand-edited files)
      parts = t.split(/\s+/);
      if (parts.length < 7) throw new Error("not a Netscape file");
    }
    // the value itself may contain tabs: everything from field 7 on belongs to it
    const domainRaw = parts[0];
    const flag = parts[1];
    const path = parts[2] || "/";
    const secureRaw = parts[3];
    const expRaw = parts[4];
    const name = parts[5];
    const value = parts.slice(6).join("\t");
    let httpOnly = false;
    let domain = domainRaw;
    if (domain.indexOf("#HttpOnly_") === 0) {
      httpOnly = true;
      domain = domain.slice("#HttpOnly_".length);
    }
    if (!domain) continue;
    const exp = parseNumberLoose(expRaw);
    const cookie = { name: name, value: value, domain: domain, path: path };
    if (flag === "FALSE") cookie.hostOnly = true;
    if (secureRaw === "TRUE") cookie.secure = true;
    else if (secureRaw === "FALSE") cookie.secure = false;
    if (httpOnly) cookie.httpOnly = true;
    if (exp != null && exp > 0) cookie.expirationDate = exp;
    else cookie.session = true;
    out.push(cookie);
  }
  if (!out.length) throw new Error("not a Netscape file");
  return out;
}

// ---------- Header String (name=value; ...) ----------

function serializeHeaderString(cookies) {
  cookiesArrayGuard(cookies);
  const parts = [];
  for (const c of cookies) {
    if (!c || !isString(c.name) || !isString(c.value)) continue;
    parts.push(c.name + "=" + c.value);
  }
  return parts.join("; ");
}

function parseHeaderStringText(text, opts) {
  if (!isString(text) || !text.trim()) throw new Error("empty header string");
  let s = text.trim();
  // tolerate a pasted "Cookie: a=b; ..." header line
  const cookiePrefix = /^cookie\s*:/i;
  if (cookiePrefix.test(s)) s = s.replace(cookiePrefix, "").trim();
  // tolerate surrounding quotes from copy-paste
  if (s.length >= 2 && ((s.charAt(0) === '"' && s.slice(-1) === '"') || (s.charAt(0) === "'" && s.slice(-1) === "'"))) {
    s = s.slice(1, -1);
  }
  if (!s) throw new Error("not a header string");
  const fallbackDomain = opts && isString(opts.fallbackDomain) ? opts.fallbackDomain.trim().replace(/^\.+/, "") : "";
  const out = [];
  for (const chunk of s.split(";")) {
    const token = chunk.trim();
    if (!token) continue;
    const eq = token.indexOf("=");
    let name;
    let value;
    if (eq === -1) {
      name = token;
      value = "";
    } else {
      name = token.slice(0, eq).trim();
      value = token.slice(eq + 1).trim();
    }
    if (!name && !value) continue;
    const cookie = { name: name, value: value };
    if (fallbackDomain) {
      cookie.domain = fallbackDomain;
      cookie.path = "/";
      cookie.hostOnly = true;
    }
    out.push(cookie);
  }
  if (!out.length) throw new Error("not a header string");
  return out;
}

// ---------- Puppeteer (Node.js) ----------

function chromeSameSiteToPuppeteer(sameSite) {
  const s = isString(sameSite) ? sameSite.toLowerCase() : "";
  if (s === "no_restriction" || s === "none") return "None";
  if (s === "strict" || s === "strict_plus") return "Strict";
  return "Lax";
}

function puppeteerSameSiteToChrome(sameSite) {
  const s = isString(sameSite) ? sameSite.toLowerCase() : "";
  if (s === "none" || s === "no_restriction") return "no_restriction";
  if (s === "strict") return "strict";
  if (s === "lax") return "lax";
  if (s === "unspecified") return "unspecified";
  return null;
}

function serializePuppeteer(cookies) {
  cookiesArrayGuard(cookies);
  const entries = [];
  for (const c of cookies) {
    if (!c || !isString(c.name) || !isString(c.value)) continue;
    const entry = {
      name: c.name,
      value: c.value,
      domain: isString(c.domain) ? c.domain : "",
      path: isString(c.path) ? c.path : "/",
      expires: typeof c.expirationDate === "number" && isFinite(c.expirationDate) && c.expirationDate > 0
        ? Math.round(c.expirationDate)
        : -1,
      httpOnly: c.httpOnly === true,
      secure: c.secure === true,
      sameSite: chromeSameSiteToPuppeteer(c.sameSite),
    };
    entries.push(entry);
  }
  return (
    "// Puppeteer cookies (Node.js) - generated by Cookie Backup and Restore\n" +
    "// Usage: const cookies = require('./cookies.js'); await page.setCookie(...cookies);\n" +
    "module.exports = " +
    JSON.stringify(entries, null, 2) +
    ";\n"
  );
}

function isPuppeteerText(text) {
  if (!isString(text)) return false;
  if (/\bmodule\.exports\b/.test(text)) return true;
  const t = text.trim();
  if (t.charAt(0) !== "[") return false;
  return /"domain"|'domain'|\bdomain\b/.test(t) && /"expires"|'expires'|\bexpires\b/.test(t);
}

// Lenient JS-array reader: our own files are strict JSON, hand-written ones
// may use single quotes, trailing commas or unquoted keys.
function parseJsArrayLenient(arraySource) {
  try {
    return JSON.parse(arraySource);
  } catch (e) {}
  let out = "";
  let i = 0;
  let quote = null;
  while (i < arraySource.length) {
    const ch = arraySource[i];
    if (quote) {
      if (ch === "\\") {
        const nx = arraySource[i + 1];
        if (quote === "'" && (nx === '"' || nx === "'")) {
          // a single-quoted JS string containing a double quote must escape
          // it for the normalized double-quoted output (and vice versa)
          out += "\\" + nx;
        } else {
          out += ch + (nx || "");
        }
        i += 2;
        continue;
      }
      if (ch === quote) {
        out += '"';
        quote = null;
      } else {
        out += ch;
      }
      i++;
      continue;
    }
    if (ch === '"' || ch === "'") {
      // normalize single-quoted strings to double-quoted
      quote = ch;
      out += '"';
      i++;
      continue;
    }
    if (ch === "/" && arraySource[i + 1] === "/") {
      while (i < arraySource.length && arraySource[i] !== "\n") i++;
      continue;
    }
    if (ch === "/" && arraySource[i + 1] === "*") {
      i += 2;
      while (i < arraySource.length && !(arraySource[i] === "*" && arraySource[i + 1] === "/")) i++;
      i += 2;
      continue;
    }
    out += ch;
    i++;
  }
  // quote bare keys: {name: 1} -> {"name": 1}
  out = out.replace(/([{,]\s*)([A-Za-z_$][A-Za-z0-9_$]*)\s*:/g, '$1"$2":');
  // drop trailing commas before } or ]
  out = out.replace(/,\s*([}\]])/g, "$1");
  return JSON.parse(out);
}

function parsePuppeteerText(text) {
  if (!isString(text) || !text.trim()) throw new Error("empty Puppeteer file");
  const start = text.indexOf("[");
  const end = text.lastIndexOf("]");
  if (start === -1 || end === -1 || end <= start) throw new Error("not a Puppeteer file");
  let arr;
  try {
    arr = parseJsArrayLenient(text.slice(start, end + 1));
  } catch (e) {
    throw new Error("not a Puppeteer file");
  }
  if (!Array.isArray(arr)) throw new Error("not a Puppeteer file");
  const out = [];
  for (const e of arr) {
    if (!e || !isString(e.name) || !isString(e.value)) continue;
    const cookie = { name: e.name, value: e.value };
    if (isString(e.domain) && e.domain) cookie.domain = e.domain;
    cookie.path = isString(e.path) && e.path ? e.path : "/";
    const exp = parseNumberLoose(e.expires != null ? e.expires : e.expirationDate);
    if (exp != null && exp > 0) cookie.expirationDate = exp;
    else cookie.session = true;
    if (typeof e.httpOnly === "boolean") cookie.httpOnly = e.httpOnly;
    else if (e.httpOnly != null) {
      const b = parseBoolLoose(e.httpOnly);
      if (b != null) cookie.httpOnly = b;
    }
    if (typeof e.secure === "boolean") cookie.secure = e.secure;
    else if (e.secure != null) {
      const b = parseBoolLoose(e.secure);
      if (b != null) cookie.secure = b;
    }
    const ss = puppeteerSameSiteToChrome(e.sameSite);
    if (ss) cookie.sameSite = ss;
    out.push(cookie);
  }
  if (!out.length) throw new Error("not a Puppeteer file");
  return out;
}

// ---------- Python Dict (requests) ----------

function serializePythonDict(cookies) {
  cookiesArrayGuard(cookies);
  const lines = [
    "# Python requests cookies - generated by Cookie Backup and Restore",
    "# Usage: import requests; requests.get(url, cookies=cookies)",
    "cookies = {",
  ];
  for (const c of cookies) {
    if (!c || !isString(c.name) || !isString(c.value)) continue;
    lines.push("    " + JSON.stringify(c.name) + ": " + JSON.stringify(c.value) + ",");
  }
  lines.push("}");
  return lines.join("\n") + "\n";
}

function isPythonDictText(text) {
  if (!isString(text)) return false;
  if (text.indexOf("{") === -1 || text.lastIndexOf("}") === -1) return false;
  return /cookies\s*=|["']\s*:\s*["']/.test(text);
}

function parsePythonStringLiteral(s, i) {
  const q = s[i];
  if (q !== '"' && q !== "'") throw new Error("not a Python dict");
  i++;
  let out = "";
  while (i < s.length) {
    const ch = s[i];
    if (ch === "\\") {
      const nx = s[i + 1];
      if (nx == null) throw new Error("not a Python dict");
      if (nx === "n") out += "\n";
      else if (nx === "t") out += "\t";
      else if (nx === "r") out += "\r";
      else if (nx === "b") out += "\b";
      else if (nx === "f") out += "\f";
      else if (nx === "v") out += "\v";
      else if (nx === "0") out += "\0";
      else if (nx === "\n") { i += 2; continue; }
      else if (nx === "x") {
        const hex = s.substr(i + 2, 2);
        if (!/^[0-9a-fA-F]{2}$/.test(hex)) throw new Error("not a Python dict");
        out += String.fromCharCode(parseInt(hex, 16));
        i += 4;
        continue;
      } else if (nx === "u" || nx === "U") {
        const len = nx === "u" ? 4 : 8;
        const hex = s.substr(i + 2, len);
        if (!new RegExp("^[0-9a-fA-F]{" + len + "}$").test(hex)) throw new Error("not a Python dict");
        const cp = parseInt(hex, 16);
        try {
          out += String.fromCodePoint(cp);
        } catch (e) {
          out += String.fromCharCode(cp & 0xffff);
        }
        i += 2 + len;
        continue;
      } else {
        out += nx;
      }
      i += 2;
      continue;
    }
    if (ch === q) return [out, i + 1];
    if (ch === "\n" || ch === "\r") throw new Error("not a Python dict");
    out += ch;
    i++;
  }
  throw new Error("not a Python dict");
}

function parsePythonDictText(text, opts) {
  if (!isString(text) || !text.trim()) throw new Error("empty Python file");
  const start = text.indexOf("{");
  const end = text.lastIndexOf("}");
  if (start === -1 || end === -1 || end <= start) throw new Error("not a Python dict");
  const body = text.slice(start + 1, end);
  const fallbackDomain = opts && isString(opts.fallbackDomain) ? opts.fallbackDomain.trim().replace(/^\.+/, "") : "";
  const out = [];
  let i = 0;
  const skipWsCommentsCommas = () => {
    while (i < body.length) {
      const ch = body[i];
      if (ch === " " || ch === "\t" || ch === "\n" || ch === "\r" || ch === ",") { i++; continue; }
      if (ch === "#") { while (i < body.length && body[i] !== "\n") i++; continue; }
      break;
    }
  };
  let anyPair = false;
  skipWsCommentsCommas();
  while (i < body.length) {
    skipWsCommentsCommas();
    if (i >= body.length) break;
    const ch = body[i];
    if (ch !== '"' && ch !== "'") throw new Error("not a Python dict");
    const keyParsed = parsePythonStringLiteral(body, i);
    const key = keyParsed[0];
    i = keyParsed[1];
    skipWsCommentsCommas();
    if (body[i] !== ":") throw new Error("not a Python dict");
    i++;
    skipWsCommentsCommas();
    if (i >= body.length) throw new Error("not a Python dict");
    let value;
    const q = body[i];
    if (q === '"' || q === "'") {
      const valueParsed = parsePythonStringLiteral(body, i);
      value = valueParsed[0];
      i = valueParsed[1];
    } else {
      // numbers / True / False / None -> stringify, anything else is invalid
      let tok = "";
      while (i < body.length && /[^,\n\r#]/.test(body[i])) { tok += body[i]; i++; }
      tok = tok.trim();
      if (/^(True|False)$/.test(tok)) value = tok === "True" ? "true" : "false";
      else if (/^None$/.test(tok)) value = "";
      else if (/^-?\d+(\.\d+)?$/.test(tok)) value = tok;
      else throw new Error("not a Python dict");
    }
    anyPair = true;
    const cookie = { name: key, value: value };
    if (fallbackDomain) {
      cookie.domain = fallbackDomain;
      cookie.path = "/";
      cookie.hostOnly = true;
    }
    out.push(cookie);
    skipWsCommentsCommas();
  }
  if (!anyPair) throw new Error("not a Python dict");
  return out;
}

// ---------- CSV (Excel / Audit) ----------

const CSV_COLUMNS = ["name", "value", "domain", "path", "secure", "httpOnly", "expirationDate", "sameSite", "hostOnly", "session", "storeId"];

function serializeCsv(cookies) {
  cookiesArrayGuard(cookies);
  const lines = [CSV_COLUMNS.join(",")];
  for (const c of cookies) {
    if (!c || !isString(c.name) || !isString(c.value)) continue;
    const row = [
      csvEscapeField(c.name),
      csvEscapeField(c.value),
      csvEscapeField(isString(c.domain) ? c.domain : ""),
      csvEscapeField(isString(c.path) ? c.path : "/"),
      c.secure === true ? "TRUE" : c.secure === false ? "FALSE" : "",
      c.httpOnly === true ? "TRUE" : c.httpOnly === false ? "FALSE" : "",
      typeof c.expirationDate === "number" && isFinite(c.expirationDate) ? String(c.expirationDate) : "",
      csvEscapeField(isString(c.sameSite) ? c.sameSite : ""),
      c.hostOnly === true ? "TRUE" : c.hostOnly === false ? "FALSE" : "",
      c.session === true ? "TRUE" : c.session === false ? "FALSE" : "",
      csvEscapeField(isString(c.storeId) ? c.storeId : ""),
    ];
    lines.push(row.join(","));
  }
  return lines.join("\n") + "\n";
}

function parseCsvRows(text) {
  const rows = [];
  let row = [];
  let field = "";
  let inQuotes = false;
  let i = 0;
  let anyField = false;
  while (i < text.length) {
    const ch = text[i];
    if (inQuotes) {
      if (ch === '"') {
        if (text[i + 1] === '"') { field += '"'; i += 2; }
        else { inQuotes = false; i++; }
      } else {
        field += ch;
        i++;
      }
      continue;
    }
    if (ch === '"' && field === "" && !anyField) {
      inQuotes = true;
      anyField = true;
      i++;
      continue;
    }
    if (ch === ",") {
      row.push(field);
      field = "";
      anyField = false;
      i++;
      continue;
    }
    if (ch === "\r" || ch === "\n") {
      row.push(field);
      field = "";
      anyField = false;
      rows.push(row);
      row = [];
      i++;
      if (ch === "\r" && text[i] === "\n") i++;
      continue;
    }
    field += ch;
    anyField = true;
    i++;
  }
  row.push(field);
  rows.push(row);
  // drop trailing empty line artifacts
  while (rows.length && rows[rows.length - 1].length === 1 && rows[rows.length - 1][0] === "") rows.pop();
  return rows;
}

function isCsvText(text) {
  if (!isString(text)) return false;
  const firstLine = text.split(/\r?\n/)[0] || "";
  const cells = firstLine.split(",").map((s) => s.trim().replace(/^"|"$/g, "").toLowerCase());
  return cells.indexOf("name") !== -1 && cells.indexOf("value") !== -1;
}

function parseCsvText(text) {
  if (!isString(text) || !text.trim()) throw new Error("empty CSV file");
  const rows = parseCsvRows(text);
  if (!rows.length) throw new Error("not a CSV file");
  const header = rows[0].map((h) => String(h).trim().toLowerCase());
  const nameIdx = header.indexOf("name");
  const valueIdx = header.indexOf("value");
  if (nameIdx === -1 || valueIdx === -1) throw new Error("not a CSV file");
  const col = (n) => header.indexOf(n);
  const domainIdx = col("domain");
  const pathIdx = col("path");
  const secureIdx = col("secure");
  const httpOnlyIdx = col("httponly");
  const expIdx = header.indexOf("expirationdate") !== -1 ? header.indexOf("expirationdate") : col("expires");
  const sameSiteIdx = header.indexOf("samesite");
  const hostOnlyIdx = col("hostonly");
  const sessionIdx = col("session");
  const storeIdIdx = col("storeid");
  const out = [];
  for (let r = 1; r < rows.length; r++) {
    const cells = rows[r];
    if (!cells.length) continue;
    if (cells.length === 1 && String(cells[0]).trim() === "") continue;
    const name = cells[nameIdx] != null ? String(cells[nameIdx]) : "";
    const value = cells[valueIdx] != null ? String(cells[valueIdx]) : "";
    if (!name && !value) continue;
    const cookie = { name: name, value: value };
    if (domainIdx !== -1 && cells[domainIdx] != null && String(cells[domainIdx]).trim() !== "") {
      cookie.domain = String(cells[domainIdx]).trim();
    }
    cookie.path = pathIdx !== -1 && cells[pathIdx] != null && String(cells[pathIdx]) !== ""
      ? String(cells[pathIdx])
      : "/";
    if (secureIdx !== -1) {
      const b = parseBoolLoose(cells[secureIdx]);
      if (b != null) cookie.secure = b;
    }
    if (httpOnlyIdx !== -1) {
      const b = parseBoolLoose(cells[httpOnlyIdx]);
      if (b != null) cookie.httpOnly = b;
    }
    if (expIdx !== -1) {
      const n = parseNumberLoose(cells[expIdx]);
      if (n != null && n > 0) cookie.expirationDate = n;
      else if (n === 0 || n === -1) cookie.session = true;
    }
    if (sameSiteIdx !== -1 && cells[sameSiteIdx] != null && String(cells[sameSiteIdx]).trim() !== "") {
      cookie.sameSite = String(cells[sameSiteIdx]).trim();
    }
    if (hostOnlyIdx !== -1) {
      const b = parseBoolLoose(cells[hostOnlyIdx]);
      if (b != null) cookie.hostOnly = b;
    }
    if (sessionIdx !== -1) {
      const b = parseBoolLoose(cells[sessionIdx]);
      if (b != null) cookie.session = b;
    }
    if (storeIdIdx !== -1 && cells[storeIdIdx] != null && String(cells[storeIdIdx]) !== "") {
      cookie.storeId = String(cells[storeIdIdx]);
    }
    out.push(cookie);
  }
  if (!out.length) throw new Error("empty CSV file");
  return out;
}

// ---------- dispatch ----------

function formatSerialize(formatId, cookies) {
  switch (formatId) {
    case "json": return serializeJson(cookies);
    case "netscape": return serializeNetscape(cookies);
    case "header": return serializeHeaderString(cookies);
    case "puppeteer": return serializePuppeteer(cookies);
    case "pydict": return serializePythonDict(cookies);
    case "csv": return serializeCsv(cookies);
    default: throw new Error("unknown format: " + formatId);
  }
}

function formatParse(formatId, text, opts) {
  switch (formatId) {
    case "json": return parseJsonText(text);
    case "netscape": return parseNetscapeText(text);
    case "header": return parseHeaderStringText(text, opts);
    case "puppeteer": return parsePuppeteerText(text);
    case "pydict": return parsePythonDictText(text, opts);
    case "csv": return parseCsvText(text);
    default: throw new Error("unknown format: " + formatId);
  }
}

function isJsonArrayText(text) {
  if (!isString(text)) return false;
  const t = text.trim();
  if (t.charAt(0) !== "[") return false;
  try {
    return Array.isArray(JSON.parse(t));
  } catch (e) {
    return false;
  }
}

function sniffPlainFormat(text, filename) {
  const name = String(filename || "").toLowerCase();
  const t = isString(text) ? text : "";
  if (/\.json$/i.test(name)) return "json";
  if (/\.csv$/i.test(name)) return "csv";
  if (/\.py$/i.test(name)) return "pydict";
  if (/\.(js|cjs|mjs)$/i.test(name)) return "puppeteer";
  if (/\.txt$/i.test(name)) return isNetscapeText(t) ? "netscape" : "header";
  if (isJsonArrayText(t)) return "json";
  if (isNetscapeText(t)) return "netscape";
  if (isCsvText(t)) return "csv";
  if (isPuppeteerText(t)) return "puppeteer";
  if (isPythonDictText(t)) return "pydict";
  return "header";
}

// ---------- encrypted envelope (.ckz holds any format) ----------

function wrapEncryptedPayload(formatId, plainText) {
  if (!isKnownFormat(formatId)) throw new Error("unknown format: " + formatId);
  return JSON.stringify({
    format: formatId,
    version: FORMAT_ENVELOPE_VERSION,
    payload: String(plainText),
  });
}

function unwrapDecryptedPayload(decrypted) {
  if (!isString(decrypted) || !decrypted) return null;
  let obj;
  try {
    obj = JSON.parse(decrypted);
  } catch (e) {
    return null;
  }
  if (Array.isArray(obj)) return { format: "json", legacy: true, cookies: obj };
  if (obj && typeof obj === "object" && !Array.isArray(obj)
      && isString(obj.payload) && isString(obj.format) && isKnownFormat(obj.format)) {
    return { format: obj.format, payload: obj.payload };
  }
  return null;
}

// filename pieces per format (plain vs encrypted)
function formatPlainSuffix(formatId) {
  switch (formatId) {
    case "json": return ".json";
    case "netscape": return "-netscape.txt";
    case "header": return "-header.txt";
    case "puppeteer": return "-puppeteer.js";
    case "pydict": return "-requests.py";
    case "csv": return "-audit.csv";
    default: return ".txt";
  }
}

function formatEncryptedSuffix(formatId) {
  if (formatId === "json") return ".ckz";
  return "-" + formatId + ".ckz";
}
